{
 "title": "Snort IDS/IPS Dashboard",
 "description": "A Snort IDS/IPS dashboard.\n\nBased on the setup from IT Security Labs:\n\nhttps://www.youtube.com/watch?v=WWitHleGFd8\n\nAnd the original Security Panel dashboard by Tal Bar-Or:\n\nhttps://grafana.com/grafana/dashboards/3099",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Métricas del sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(timestamp) * 1000 AS time,\r\n  temperature AS \"Temperatura\"\r\nFROM system_metrics\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp ASC;\r\n"
    }
   ]
  },
  {
   "title": "Datos del sistema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(timestamp) * 1000 AS time,\r\n  cpu_usage AS \"Uso de CPU %\",\r\n  temperature AS \"Temperatura\",\r\n  disk_usage AS \"Uso de disco\"\r\nFROM system_metrics\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp ASC;\r\n"
    }
   ]
  },
  { "title": "Severidad de eventos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Alertas de severidad alta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "priority:1 AND application_name:snort-alerts",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) * 1000 AS time,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE priority = 1\r\n  AND timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) DIV 60\r\nORDER BY time ASC;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Alertas de severidad media",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "priority:2 AND application_name:snort-alerts",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) * 1000 AS time,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE priority = 2\r\n  AND timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) DIV 60\r\nORDER BY time ASC;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Alertas de severidad baja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "priority:3 AND application_name:snort-alerts",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) * 1000 AS time,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE priority = 3\r\n  AND timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) DIV 60\r\nORDER BY time ASC;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Metricas de eventos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Alertas por severidad",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Low",
     "bucketAggs": [
      {
       "fake": true,
       "field": "priority",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "3", "type": "count" }
     ],
     "query": "priority:3 AND application_name:snort-alerts",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(timestamp) * 1000 AS time,\r\n  COUNT(*) AS value,\r\n  CASE\r\n    WHEN priority = 1 THEN 'Severa'\r\n    WHEN priority = 2 THEN 'Media'\r\n    WHEN priority = 3 THEN 'Baja'\r\n  END AS metric\r\nFROM alerts\r\nWHERE timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY\r\n  metric,\r\n  UNIX_TIMESTAMP(timestamp) DIV 60\r\nORDER BY time ASC;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top tipos de alertas",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "4",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "Low -", "query": "priority:3" },
         { "label": "Medium -", "query": "priority:2" },
         { "label": "High -", "query": "priority:1" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "classification",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      {
       "field": "alert_description",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:snort-alerts",
     "rawSql": "SELECT\r\n  CONCAT(\r\n    CASE\r\n      WHEN priority = 1 THEN 'High'\r\n      WHEN priority = 2 THEN 'Medium'\r\n      WHEN priority = 3 THEN 'Low'\r\n    END,\r\n    ' - ',\r\n    msg\r\n  ) AS metric,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY priority, msg\r\nORDER BY value DESC;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top protocolos",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      {
       "field": "alert_description",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:snort-alerts",
     "rawSql": "SELECT\r\n  proto AS metric,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY proto\r\nORDER BY value DESC;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst_addr_country_code",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "ip",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:snort-alerts",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Destination by Country",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dst_addr_country_code",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "application_name:snort-alerts",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_addr_country_code",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "ip",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:snort-alerts",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Source by Country",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src_addr_country_code",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "application_name:snort-alerts",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top IPs de origen",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_addr",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:snort-alerts",
     "rawSql": "SELECT\r\n  src_addr AS metric,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY src_addr\r\nORDER BY value DESC\r\nLIMIT 10;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top puertos de destino",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:snort-alerts",
     "rawSql": "SELECT\r\n  CASE dst_port\r\n    WHEN 20 THEN '20 - FTP'\r\n    WHEN 21 THEN '21 - FTP'\r\n    WHEN 22 THEN '22 - SSH'\r\n    WHEN 23 THEN '23 - Telnet'\r\n    WHEN 25 THEN '25 - SMTP'\r\n    WHEN 53 THEN '53 - DNS'\r\n    WHEN 80 THEN '80 - HTTP'\r\n    WHEN 110 THEN '110 - POP3'\r\n    WHEN 143 THEN '143 - IMAP'\r\n    WHEN 443 THEN '443 - HTTPS'\r\n    WHEN 3306 THEN '3306 - MySQL'\r\n    WHEN 3389 THEN '3389 - RDP'\r\n    WHEN 8080 THEN '8080 - HTTP-Alt'\r\n    ELSE CONCAT(dst_port, ' - Unknown')\r\n  END AS metric,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE dst_port IN (\r\n    20, 21, 22, 23, 25, 53, 80, 110, 143, 443, 3306, 3389, 8080\r\n)\r\n  AND timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY metric\r\nORDER BY value DESC\r\nLIMIT 10;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top IPs de destino",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst_addr",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:snort-alerts",
     "rawSql": "SELECT\r\n  dst_addr AS metric,\r\n  COUNT(*) AS value\r\nFROM alerts\r\nWHERE timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY dst_addr\r\nORDER BY value DESC\r\nLIMIT 10;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Protocole vs Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dataset": "performance_schema",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "application_name:snort-alerts",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) * 1000 AS time,\r\n  COUNT(*) AS value,\r\n  proto AS metric\r\nFROM alerts\r\nWHERE timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nGROUP BY\r\n  proto,\r\n  UNIX_TIMESTAMP(STR_TO_DATE(timestamp, '%Y-%m-%d %H:%i:%s')) DIV 60\r\nORDER BY time ASC;\r\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  timestamp AS \"Hora\",\r\n  msg AS \"Alerta\",\r\n  src_addr AS \"Origen\",\r\n  dst_addr AS \"Destino\",\r\n  dst_port AS \"Puerto\",\r\n  CASE\r\n    WHEN msg LIKE '%PROTOCOL%' THEN 'Alerta de protocolo'\r\n    WHEN msg LIKE '%http%' THEN 'HTTP'\r\n    ELSE 'Tráfico desconocido'\r\n  END AS \"Clase de alerta\",\r\n  CASE priority\r\n    WHEN 1 THEN 'Alta'\r\n    WHEN 2 THEN 'Media'\r\n    WHEN 3 THEN 'Baja'\r\n    ELSE 'Desconocida'\r\n  END AS \"Severidad\"\r\nFROM alerts\r\nWHERE timestamp >= FROM_UNIXTIME(${__from} / 1000)\r\n  AND timestamp <= FROM_UNIXTIME(${__to} / 1000)\r\nORDER BY timestamp DESC\r\nLIMIT 100\r\n"
    }
   ]
  }
 ]
}